### PR TITLE
Dev0.1

### PR DESCRIPTION
**Pull request by PerezImanol**
Model, package structure and interfaces designed

### CODE REVIEW

**Comment by ysasgon** [comment]
Looks good for me.

**Comment by Javier-Fermin** [comment]
Everything seems fine for me, go ahead and merge it

**Comment by Javier-Fermin** [comment]
Everything seems fine for me, go ahead and merge it

**Comment by Javier-Fermin** [comment]
Everything seems fine for me, go ahead and merge it

**Comment by PerezImanol** [comment]
Merging

**Pull request merged**
